name: Auto WZML-X Mirror Bot

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch: 


jobs:
  run-sync-service:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Downloading the Script
        run: |
          wget https://gist.githubusercontent.com/Sibu07/24980aa25dd87d3ed4f7693b6fae1d9c/raw/wzmlx.sh
      - name: Permission
        run: |
           chmod 777 wzmlx.sh
      - name: Running the Script
        run: |
           ./wzmlx.sh
           
      - name: Cancel workflow
        run: |
          echo "Cancelling the workflow"
          curl -X POST -H "Authorization: Bearer ${{ secrets.A_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel
